Improvement/back end for logging
UberBarber/UberBarber pull request #17
Opened 2023-01-20 21:45 UTC by Cialkowski

create new class with databse queries, create logging in functionality

2023-01-22 17:01 UTC, Kacprodyl requested changes
except two little mistakes, whole pull request looks nice

2023-01-22 17:01 UTC, Borzygniew commented on UberBarber/UberBarber/View/LoginView.xaml.cs
> -            //TODO
Todo deleted, where docstring?

2023-01-22 17:01 UTC, Borzygniew commented on UberBarber/UberBarber/database/DatabaseQueries.cs
> +
remove unnecessary blank lines

2023-01-22 18:15 UTC, Cialkowski commented on UberBarber/UberBarber/View/LoginView.xaml.cs
> -            //TODO
done

2023-01-22 18:16 UTC, Cialkowski commented on UberBarber/UberBarber/database/DatabaseQueries.cs
> +
done

2023-01-22 19:12 UTC, Kacprodyl approved these changes
![Zrzut ekranu 2023-01-11 213744](https://user-images.githubusercontent.com/103364909/213935293-c1214c9d-bd32-4e07-bc13-632343b55106.png)

2023-01-23 10:27 UTC, goflyy approved these changes

2023-01-23 10:33 UTC, merged