Improvement/g UI main window
UberBarber/UberBarber pull request #30
Opened 2023-01-31 23:38 UTC by goflyy

### **Simple MainWindow UI**

It consists of three main sections:

1. Menu
- It has buttons thanks to which we will be able to switch from view to view
_Example buttons have been added to it_

2. Content
- The main section where the functionalities of the program will be displayed
_Margins have been added to keep everything consistent and clear (wihout specifed content) _

3. User Options
- It's fun here because I got carried away by fantasy
_Added buttons: notifications, email and clock (I don't know what this clock is for, I couldn't think of anything else, and I didn't have a logout icon because it's not free). I also added a "textbox" in which the name of the logged in user will be displayed._

Here you have free icons that we can use instead of the clock icon :)
[https://fontawesome.com/search?o=r&m=free](url)

![image](https://user-images.githubusercontent.com/75216504/215904034-8a5e2142-4654-45ff-8dc9-c5850d0b01e4.png)

2023-02-01 00:09 UTC, Kacprodyl requested changes
![image](https://user-images.githubusercontent.com/103364909/215912800-1de0d5f0-8943-4a54-9345-5eb65604de95.png)

dashboard window doesnt looks like you attached on pr description

2023-02-01 12:36 UTC, Borzygniew approved these changes
🍒

2023-02-01 19:58 UTC, MSkrzypinski approved these changes
LGTM

2023-02-02 15:01 UTC, Cialkowski approved these changes

2023-02-02 15:03 UTC, merged